### ISSUE TITLE
[Enhancement] Support new Captcha Webhook

### ISSUE THREAD

**Issue by spammer23** [RocketMap/PokeAlarm#297]
## Enhancement Description

Support the new PR [#1754](https://github.com/RocketMap/RocketMap/pull/1754) 

Now you get the following ERROR:
2017-01-27 09:53:27,063 [     alarm_manager] [  ERROR] Error while processing request: 'token_needed'
2017-01-27 09:53:39,828 [     alarm_manager] [   INFO] Captcha notification for account XYZ was triggered
2017-01-27 09:53:39,830 [     alarm_manager] [  ERROR] Error while processing request: 'token_needed'

## Use cases

To be informed about new Captchas

**Comment by neskk** [comment]
The structure of webhook updates is still up for discussion, so far the structure I follow is this:
```
  wh_message = {'status_name': args.status_name,
                  'status': 'error',
                  'account': status['username'],
                  'captcha': status['captcha'],
                  'time': 0}
```
Every field is pretty much self-explanatory:
 - status_name: instance name (note that it can be `None`).
 - captcha: number of captchas that the current username has encountered while scanning
 - time: provides some insight on how long the captcha took to be solved.

We have 4 status codes:
- encounter: used whenever a captcha is found
- error: an unexpected error occurred
- success: account was uncaptcha'd
- failure: token retrieved but failed to verify challenge.

**Comment by spammer23** [comment]
@kvangent With the update today, the PR was merged.

**Comment by kvangent** [comment]
@neskk @spammer23  I haven't tried the manual captcha-solving yet. What is it you would like this to do? Just a notification with the account name? It doesn't look like there is enough information to send a link to solve.

Ideally a default template of what you would like to see would be great.

**Comment by neskk** [comment]
@kvangent Most messages are just informative and require no action.
I have a fork that used to treat captcha messages and send them to a specialized channel in Slack.
Some simple support for displaying captcha messages in some channel would be great. People can track better when captchas arrive and how much time they're taking to be solved. This feature should be able to be enabled/disabled in config.

**Comment by sLoPPydrive** [comment]
I also supported captcha notifications before PR #1754 was merged or even fully developed. I found 2 major use cases:

1. Personal use: Get to know about Captchas ASAP, the more info the better (account name, instance name for example) and also get notifications about successfully solving Captchas (or failures or timeouts).
2. Community use: Push captcha notification to a special channel with as few infos as possible but maybe include the bookmarklet URL and number of captchas to solve.

The new configuration I introduced looked like that:
```
'captcha': {
    # 'chat_id': If no default, required
    'title': 'dummy',
    'body': "<captcha_counter> captcha(s) need to be solved via <bookmarklet_url>.",
    'body_no_more_captcha': "No more captcha to solve! Thank you very much! &lt;3",
    'text_encounter': "Captcha for account <account> on instance <status_name>!",
    'text_timeout': "Timeout waiting for captcha token for account <account> on instance <status_name>.",
    'text_solved': "Solved captcha for account <account> on instance <status_name>.",
    'text_failed': "Failed solving captcha for account <account> on instance <status_name>."
}
```

Note that this is currently not compatible with the latest Rocket Map release because the notification events were named differently (e.g. success instead of solved). For implementation details you might want to take a look at my fork: https://github.com/sLoPPydrive/PokeAlarm/tree/DEBUG (I only implemented captcha notifications for Telegram)

**Comment by spammer23** [comment]
From my point it's enough to know that account xyz needs a captcha and a notification if the captcha failed. No need for a link.
But the ideas of @sLoPPydrive are perfect - just some "False" entries for me

**Comment by jaggles** [comment]
Same here, I relied heavily on @sLoPPydrive 's DEBUG branch to get notified via Telegram any time I'd encountered a captcha. I could then use my phone to manually solve it.

@sLoPPydrive I just installed your multi_conditions branch and it seems to be accepting the new verbiage from RocketMap fine, but it won't trigger the Telegram alert when a captcha is encountered. (I.e. instead of the error message it says "Captcha notification for account XXX was triggered" again. But the Telegram won't trigger...

**Comment by MARTINI1** [comment]
+1 to the ideas of @sLoPPydrive, really cool, especially the community use that is the most interesting I see

If you can do a test version with v3 and discord or slack support (better discord) it would be great to test and see if it works correctly

Good job ;)

**Comment by kvangent** [comment]
Is anyone interested in any filtering for these? Or just a straight up message with the given fields?

**Comment by kvangent** [comment]
I've added initial support. So far only working with Discord.

**Comment by neskk** [comment]
Thank you @kvangent.
I think you forgot `status` field in captcha struct.
I suggest that filtering could be based on `mode` and `status` with the ability to disable/enable messages from being sent to a specified channel where captcha messages are delived. If I have some spare time I'll try to implement a Slack alarm.
I also think it's nice to have a global kill switch to ignore `captcha` messages (and also `scheduler` status messages).

----
Scheduler status messages are even simpler than captcha ones:
```
wh_queue.put(('scheduler', {'name': scheduler_name,
                                        'instance': args.status_name,
                                        'tth_found': tth_found,
                                        'spawns_found': spawns_found}))
```
- `name` string that contains scheduler's name - currently only `SpeedScanner` outputs these messages.
- `tth_found` float with the percentage of the TTH found for discovered spawn points.
- `spawns_found` integer with the current count of spawn points found.
