### ISSUE TITLE
Config does not allow for multiple gmap keys to be used

### ISSUE THREAD

**Issue by Goldclownfish** [RocketMap/PokeAlarm#442]
Would like to see the ability to enter multiple google map keys to be used in order to prevent errors once the key has reached its daily limit.

**Comment by FrostTheFox** [comment]
@kvangent I'm not familiar with PokeAlarm myself since I have marginally not looked at the code or played around with it myself since I do not run a map, so I don't know if this is possible and is being overlooked or something else, however, if there is a solution to the issue, or for some reason it is denied, it would be helpful to place a reason here along with the closing instead of simply closing the issue.

**Comment by Goldclownfish** [comment]
I apologize for not following the format. I am on mobile An it’s very difficult to follow that when the comment box is completely filled. Your more then welcome to attempt to follow the format yourself on iOS an find out exactly how much fun it is to attempt to scroll through it to enter the info into the template correctly. Sorry for that but I did not have an hour to attempt to do so An thought it would be viewed instead of simply closed without a word.

**Comment by kvangent** [comment]
At the beginning of the issue template the following warning is displayed:
```
!--- ALL ISSUES CREATED NOT USING ONE OF THE BELOW ISSUE TEMPLATES WILL BE CLOSED WITHOUT RESPONSE --- 
!--- ALL ISSUES CREATED NOT USING ONE OF THE BELOW ISSUE TEMPLATES WILL BE CLOSED WITHOUT RESPONSE --- 
!--- ALL ISSUES CREATED NOT USING ONE OF THE BELOW ISSUE TEMPLATES WILL BE CLOSED WITHOUT RESPONSE --- 
!--- ALL ISSUES CREATED NOT USING ONE OF THE BELOW ISSUE TEMPLATES WILL BE CLOSED WITHOUT RESPONSE ---
```
(At some point my comments lost their points, I'm not sure how this happened)

When I closed issues with a comment, people were upset that I took the time to comment rather than answer their question. As such, I made it my policy to just close issues without response. I left the warning so that it is obvious when creating an issue what will happen.

However @Goldclownfish, I have taken you feedback into account and have updated the issue templates to have less width and to be more readable. They will take effect when I merge dev into master (which hopefully will happen in the next couple of days). Since I don't own an iOS device I can't test it's readability. However if you still have problems with readability, I suggest opening future issues from a device with a larger screen.
